### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by SteveShaffer** [veritone/veritone-app-boilerplate-react#9]
The current boilerplate includes no favicon.  I think a couple of our internal apps did alternate implementations.  I'll dig them up and paste here and we can discuss.

**Comment by SteveShaffer** [comment]
### Option 1
Add this `links` section to `.enutrinorc.use[0][1].html`:
```
          links:[
            {
              href: "https://static.veritone.com/assets/favicon/apple-touch-icon.png?v=lkgpRBRLYl",
              rel: "apple-touch-icon",
              sizes: "180x180"
            },
            {
              href: "https://static.veritone.com/assets/favicon/favicon-32x32.png?v=lkgpRBRLYl",
              rel: "icon",
              sizes: "32x32",
              type: "image/png"
            },
            {
              href: "https://static.veritone.com/assets/favicon/favicon-16x16.png?v=lkgpRBRLYl",
              rel: "icon",
              sizes: "16x16",
              type: "image/png"
            },
            {
              href: "https://static.veritone.com/assets/favicon/safari-pinned-tab.svg?v=lkgpRBRLYl",
              rel: "mask-icon",
              color: "#597cb1"
            },
            {
              href: "https://static.veritone.com/assets/favicon/favicon.ico",
              rel: "shortcut icon",
              type: "image/x-icon"
            }
          ]
```

### Option 2
`yarn install react-favicon` and
```
<Favicon url="https://static.veritone.com/assets/favicon/favicon-32x32.png" />
```

### Option 3
Just add a `favicon.ico` to project root

**Comment by SteveShaffer** [comment]
@olslash thoughts?

**Comment by olslash** [comment]
I don't know a whole lot about this, but given that the .ico format is container for many sizes, would ie. option 1 need all those entries? or can it just be a single ICO?

either way, I'd go with option 1 because we're already generating all the basic markup for index.html from there... nice to have all that in one place

**Comment by SteveShaffer** [comment]
Option 1's my top choice too. From what I know about option 1, they should be different pngs usually.  They're used for things like phone app icons or dock icons or whatever as well as the favicon.
